export const FORMULARIO_PROYECTO = 'PROYECTO_PROYECTO'
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS'
export const AGREGAR_PROYECTOS = 'AGREGAR_PROYECTOS'
export const VALIDAR_FORM = 'VALIDAR_FORM'
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL'
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO'

export const TAREAS_PROYECTO = 'TAREAS_PROYECTO';
export const AGREGAR_TAREAS = 'AGREGAR_TAREAS';
export const VALIDAR_TAREA = 'VALIDAR_TAREA';